services:
  backend:
    build:
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_SERVER_PORT=8000
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_HIBERNATE_PROPERTIES_HIBERNATE_FORMAT_SQL=true
      - JWT_ACCESS_SECRET=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - postgres
    ports:
      - 8000:8000
    networks:
      - sspa-postgress

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped
    networks:
      - sspa-postgress

networks:
  sspa-postgress:
    external: true

volumes:
  postgres: